### ISSUE TITLE
stack trace when trying to donwload

### ISSUE THREAD

**Issue by Jibede** [JulesGrillot/plugin_bd_topo_extractor#22]
### What is the bug or the crash?

Je lance le téléchargement, j'ai un stack trace au bout d'un moment. Et le téléchargement n'avance pas.

Voici le stack trace :

Une erreur est survenue lors de l'éxécution du code Python: 

_core.QgsProcessingException: Impossible de créer la couche en mémoire. 
Traceback (most recent call last):
  File "C:\Users/dodeur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bd_topo_extractor\plugin_main.py", line 250, in handle_finished
    self.processing()
  File "C:\Users/dodeur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bd_topo_extractor\plugin_main.py", line 314, in processing
    request = WfsRequest(
  File "C:\Users/dodeur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bd_topo_extractor\processing\wfs_request.py", line 70, in __init__
    self.create_layer()
  File "C:\Users/dodeur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bd_topo_extractor\processing\wfs_request.py", line 206, in create_layer
    self.final_layer = processing.run(
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins\processing\tools\general.py", line 108, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins\processing\core\Processing.py", line 187, in runAlgorithm
    ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
  File "C:\PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 72, in execute
    results, ok = alg.run(parameters, context, feedback, {}, False)
_core.QgsProcessingException: Impossible de créer la couche en mémoire.

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.28.0-Firenze Firenze, ed3ad0430f3 

Chemin Python :
C:\Users/dodeur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\csv_tools
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python
C:/Users/dodeur/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/dodeur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.28.0\bin\python39.zip
C:\PROGRA~1\QGIS32~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.28.0\bin
C:\Users\dodeur\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/dodeur/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/dodeur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\joinmultiplelines
C:\Users\dodeur\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs
C:\Users/dodeur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\dodeur\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

### Steps to reproduce the issue

run the interface.
draw a zone (commune de locmariaquer, morbihan)
select features to download :

- batiments, 
- constructions ponctuelle, 
- construction lineaires, 
- equipements de transport, 
- ligne electrique, 
- poste de transformation, 
- pylone, 
- reservoir, 
- routes numérotée, 
- terrains de sport, 
- troncon de route, 
- zones d'habitation, 
- zone d'activité ou td'intérert, 
- zone de vegetation

conserver les donnée intersectant
CRS : WGS84 - 3857

![Capture](https://github.com/JulesGrillot/plugin_bd_topo_extractor/assets/144351366/73e157d3-4b4d-467f-8a36-64fbbe868d71)

### Versions

qgis 3.28.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the official roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Jibede** [comment]
Pour compléter, dans le journal des messages WFS de QGIS, j'ai :

2023-10-10T09:14:13     WARNING    Échec de l'analyse de la réponse DescribeFeatureType pour l'URL request='GetFeature' service='wfs' srsName='EPSG:4326' table='' title='BDTOPO_V3:construction_lineaire' typename='BDTOPO_V3:construction_lineaire' url='https://wxs.ign.fr/topographie/geoportail/wfs' version='auto' sql=SELECT * FROM "BDTOPO_V3:construction_lineaire" as t1 WHERE ST_Intersects(t1.geometrie, ST_GeometryFromText('Polygon ((-2.980664692385214 47.55071308980829, -2.924506135475583 47.55071308980829, -2.924506135475583 47.56693495866456, -2.980664692385214 47.56693495866456, -2.980664692385214 47.55071308980829))', 4326)), typeName: BDTOPO_V3:construction_lineaire Il s'agit probablement d'un schéma pour des entités complexes
2023-10-10T09:14:13     WARNING    Rapport d'erreur WFS (code=OperationProcessingFailed texte=Error occurred getting featuresUnable to obtain connection: Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             FATAL: the database system is in recovery mode)
2023-10-10T09:14:13     WARNING    Rapport d'erreur WFS (code=OperationProcessingFailed texte=Error occurred getting featuresUnable to obtain connection: Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             FATAL: the database system is in recovery mode)
2023-10-10T09:14:13     WARNING    Rapport d'erreur WFS (code=OperationProcessingFailed texte=Error occurred getting featuresUnable to obtain connection: Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             FATAL: the database system is in recovery mode)
2023-10-10T09:14:13     WARNING    Rapport d'erreur WFS (code=OperationProcessingFailed texte=Error occurred getting featuresUnable to obtain connection: Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             FATAL: the database system is in recovery mode)
2023-10-10T09:14:13     WARNING    Rapport d'erreur WFS (code=OperationProcessingFailed texte=Error occurred getting featuresUnable to obtain connection: Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             FATAL: the database system is in recovery mode)
2023-10-10T09:14:13     WARNING    Rapport d'erreur WFS (code=OperationProcessingFailed texte=Error occurred getting featuresUnable to obtain connection: Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             FATAL: the database system is in recovery mode)
2023-10-10T09:14:13     WARNING    Rapport d'erreur WFS (code=OperationProcessingFailed texte=Error occurred getting featuresUnable to obtain connection: Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             FATAL: the database system is in recovery mode)
2023-10-10T09:14:13     WARNING    Rapport d'erreur WFS (code=OperationProcessingFailed texte=Error occurred getting featuresUnable to obtain connection: Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             FATAL: the database system is in recovery mode)
2023-10-10T09:14:13     WARNING    Rapport d'erreur WFS (code=OperationProcessingFailed texte=Error occurred getting featuresUnable to obtain connection: Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             FATAL: the database system is in recovery mode)
2023-10-10T09:14:13     WARNING    Rapport d'erreur WFS (code=OperationProcessingFailed texte=Error occurred getting featuresUnable to obtain connection: Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             Cannot create PoolableConnectionFactory (FATAL: the database system is in recovery mode)
             FATAL: the database system is in recovery mode)

**Comment by JulesGrillot** [comment]
Ça fait un moment que j'ai pas travaillé sur le plugin, mais j'ai refait une release récemment, si tu as le temps de tester pour voir si le bug est toujours présent ?

**Comment by Jibede** [comment]
Super ça fonctionne. J'ai réussi à extraire la donnée dans un extent.
